version: '3.1'

volumes:
  wordpress_vol:
  db_vol:

networks:
  wordpress_rede:
    driver: bridge

services:
  wordpress:
    image: wordpress
    restart: always
    networks:
      - wordpress_rede
    ports:
      - 8080:80
    volumes:
      - wordpress_vol:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: WORD-TESTE
      WORDPRESS_DB_NAME: DB_DEV

  db:
    image: mysql:5.7
    restart: always
    networks:
      - wordpress_rede
    ports:
      - 3306:3306
    volumes:
      - db_vol:/var/lib/mysql
    environment:
      MYSQL_DATABASE: DB_DEV
      MYSQL_USER: admin
      MYSQL_PASSWORD: WORD-TESTE
      MYSQL_ROOT_PASSWORD: WORD-TESTE


    
